### ISSUE TITLE
Demo Logistic regression has red crosses

### ISSUE THREAD

**Issue by trotor** [gtkfi/ArcSDM#46]
When copied to work directory demo doesn't work correctly.

**Comment by trotor** [comment]
Not replicable anymore with new dataset. Closing

**Comment by irvcaza** [comment]
In the **screenshot** showed by @trotor : 
![screenshot](https://user-images.githubusercontent.com/15790161/28367224-52bc9020-6c90-11e7-82b1-706469bb42d4.png)
The problem can be observed, the field "_Store relative path names (instead of absolute paths)_" must be **checked**.
The reason why this is not reproducible by you is because the the absolute path exist in your computer, in mine it doesn't.
The solution might be 
1. **Check** the mentioned field
2. Save the project
3. Upload the project to dropbox
4. Update README.md pointing to the new direction

**Comment by irvcaza** [comment]
I can confirm this trouble is not longer present in the [new](https://www.dropbox.com/s/q8jw6awnrl1q2t0/ArcSdm_DemoData.zip?dl=0) demo data
