### ISSUE TITLE
Calculate Weights type autofill

### ISSUE THREAD

**Issue by DarthSysmon** [gtkfi/ArcSDM#58]
Hello again,

The autofill feature of weights table name in the Calculate Weights tool is neat. However, it requires that Type is set before the Evidence Raster Layer is chosen. When the raster layer is added, the name autofills and comes up with the default ending (_CD) since the Type field defaults to Descending.

Maybe that can be circumvented by leaving Type empty and now have the autofill happen until a Type has been selected? Mainly cosmetic.

![autofillissue](https://user-images.githubusercontent.com/25653028/31260545-251946fa-aaab-11e7-93dd-d2fc4ee45acb.JPG)

**Comment by trotor** [comment]
Hi, very good tip! Actually when I explicitly didn't set it to anything it chose the first option in the list and was filled, when I set it to "" it seems to work like you suggest.

There is kind of bug there, deep in both Pro and desktop. Parameter "hasChanged" is not obeyed and and I can't make it work correctly on autoset or it prevents user from editing the output table name afterwards. This solution perhaps helps! 
Thanks, closing this as this is fixed in next release (xx.xx.22 later today).
