### ISSUE TITLE
Calculate Weights and perfect correlation

### ISSUE THREAD

**Issue by DarthSysmon** [gtkfi/ArcSDM#66]
Hi there.

The SDM toolbox seems to still not be able to handle perfect correlations. The issue is that the the calculated Contrast standard deviation jumps from a low value to ten when all training points are picked up by the test. This drops the StudC value to a low value, where it should probably stay high. 

I ran a series of tests on a buffered training dataset, using 1, 2 and 4 km buffers around a set of 31 training points. Then I moved one point just outside the largest buffer distance and ran the tests again. You can see the result in the attached table; something goes wrong with the calculation of S_CONTRAST when the correlation is perfect: The S_CONTRAST approximates 10, where it should probably approximate 1. If a training point is moved to the OUT area, S_CONTRAST approximates 1. From the GoCAD 3D SDM weights calculation, I see S_CONTRAST go to 1 when all training points are picked up (and C then becomes equal to StudC).

The StudC calculated on imperfect correlations seem okay, so it may not be a general error in calculating S_CONTRAST. Could it be an error introduced in a patch to avoid a divide-by-zero issue? Either way, the S_CONTRAST for perfect correlation is not correct.

Cheers,
S

[PerfectCorrelation.xlsx](https://github.com/gtkfi/ArcSDM/files/1373999/PerfectCorrelation.xlsx)

**Comment by tachyon-work** [comment]
Hi guys,

I just spent the morning going through python scripts trying to figure this out, and I think I have found the problem. If you look at calculateweights.py, on line 83 where there is a bunch of if statements to deal with traps, it sets db=db-0.01 if all real training points are in a categorical class. If you then follow this through with the equations for vp (line 123), vm (line 138), and sc (standard deviation of the contrast; line 143), you end up with the following:
`

s | 200000 | 200000
-- | -- | --
b | 10000 | 10000
ds | 20 | 20
db | 19.99 | 19.01
vp | 0.05012521 | 0.05270408
vm | 100.00000526 | 1.01010627
stdc | 10.00250621 | 1.03092694

`
As you approach a perfect correlation, the sc value should approach 1. If you modify the equation for the case where db=ds such that db=db-0.99 instead as I do in the table above, you approach the correct standard deviation for the contrast. Therefore you end up with a more accurate stud_cnt value, which is what we've been having problems with. If we want the SDM to automatically choose maps and thresholds based on contrast and stud_cnt, it needs more accurate stud_cnt values. 

This is also the reason why the W_STD values for the Out class in a binary map with a perfect correlation are wrong, because on line 487 the W_STD is taken from the maxWminus_Std from the In class. And as noted above, the calculation of this value (vm) is an issue.

I hope this helps and that it can be resolved in the next update :)

Cheers
Arianne

**Comment by trotor** [comment]
Hey, so sorry. I implemented the "-0.99" for testing but my response to this issue has been lost! So sorry

**Comment by trotor** [comment]
So waiting for user input after updating to version .24

**Comment by tachyon-work** [comment]
Great! Just tested using Calculate Weights tool and also ran the Grand WofE (which had an error at another point which there's a separate bug report for already, but it created the tables with the correct weights). 

I think this can now be closed. Probably worth making a note of the change in the documentation just in case people are trying to compare old SDM results with new SDM results and wondering why there's a discrepancy?

**Comment by tachyon-work** [comment]
I have just noticed another issue. I had run the previous test using categorical. If you run this tool using ascending or descending, the problem remains with the WMINUS and S_WMINUS values when you hit a perfect correlation.

See image:
![image](https://user-images.githubusercontent.com/32659237/32863728-544f899e-cac1-11e7-8e6c-1e01fa7f9725.png)

**Comment by trotor** [comment]
I will take a look if there are multiple entries for those -0.01 values and will replace them.

**Comment by trotor** [comment]
Some fixes made, will still need further work

**Comment by trotor** [comment]
This further corrected/fixed on 5.00.27 Waiting input

**Comment by DarthSysmon** [comment]
Tested this in a new model in ArcMap 10.5. Workspace and Scratch set up as geodatabases. 

First issue encountered is that the Mask has to be set to a shapefile in Environments for the Calculate Weights tool to work. It should be a raster.

Running the Calculate Weights tool crashes similarly for CA and CT tests, with out without no data (see attached images). 

We cannot test further until this has been fixed and we can see the output weights tables.
![catest_crash](https://user-images.githubusercontent.com/25653028/34501681-eb2092b8-f074-11e7-947a-d93cbeba809c.JPG)
![catest_crash_nd](https://user-images.githubusercontent.com/25653028/34501695-f1b0c418-f074-11e7-80a1-09321bcef623.JPG)

**Comment by trotor** [comment]
Hi, does mask have to be rasterdataset? rasterlayers are supported and should work. I will further study dataset as mask as soon as I get one from the demo data team if it is necessary. I don't have access to one at the moment and will forward this to them.

Other bug seems curious as I can't replicate it, but that line commented and fixed on new version.

**Comment by DarthSysmon** [comment]
Hi there. Yes, the mask has to be a raster dataset. For some reason we can only use shapefiles at the moment.

Thanks for looking into the other bug: We are running into it in 10.3 and 10.5, using different model workspaces and model files. So I think the problem is in the build that was uploaded here.

**Comment by DarthSysmon** [comment]
Another issue related to this: The Calculate Weights tool running an ascending test on a raster generated from buffered training data (perfect correlation) runs into two issues, in addition to the issue of generating an error in execution. At least it still generates a table:

Firstly, the issue related to small IN regions is still relevant. As is notable in the image below, the first 11 classes are all 0 (550 m buffer). The area of each class is less than the total area of the unit cells, and for some reason that makes the values revert to zero. That is still a bug:
![contrast_ca](https://user-images.githubusercontent.com/25653028/34543999-a9976d24-f148-11e7-9b32-107737c34f08.JPG)

The other issue is with the weights. Class 2 (IN) is only the "zero" regions that are smaller than the total unit cell area. Class 1 is negative. Something is still going wrong when calculating weights for perfect correlations.
[PFContrast_CA.xlsx](https://github.com/gtkfi/ArcSDM/files/1601983/PFContrast_CA.xlsx)

**Comment by trotor** [comment]
Thank you  for the explanation! I will forward this to Vesa and others for
debugging - I need help from them so I can fully understand the problem.

To be sure: This was working on original sdm?

**Comment by tachyon-work** [comment]
No, this issue existed on the original SDM as well. Just ran it to check:
![image](https://user-images.githubusercontent.com/32659237/34582109-bb530294-f1f7-11e7-8526-89d0c905ee49.png)
